### ISSUE TITLE
Ontwerp squadpage

### ISSUE THREAD

**Issue by lisavanmansom** [zoepje/your-tribe-for-life-squad-page#1]
Ontwerp van squadpage per persoon (woensdag)

**Comment by MisahSaid** [comment]
simba ontwerp!!! (ontwerp dat gekozen is om uit te voeren) 

https://www.figma.com/design/ih7XPB0nlA6XIDjn3kYCP6/prototype-ontwerp%2C-squadpage-(L2)?node-id=0-1&t=h2c0rl0xnlK68tJF-1

**Comment by lemuelmgsn** [comment]
Mijn ontwerp

https://www.figma.com/design/AU2cCXvbwcPMzcu8I3Tzg7/Squadpage-sem-3?node-id=160-2&node-type=CANVAS&t=84MnfBI4yGCzaiUI-0

**Comment by TygoWolven** [comment]
Mijn 2 ideeën voor de squadpage.

**Een draaimolen:**
Waarbij alle leerlingen in een karretje staan. Je kunt de draaimolen ronddraaien en meer informatie bekijken over de leerling.

**Een magisch boek:**
Waarbij elke pagina van het boek word toegewezen naar een leerling, waar direct meer informatie te lezen is.

<img width="300" src="https://github.com/user-attachments/assets/4ea84a4c-f9cd-4ddf-9cf9-6b725cff93e1">

**Comment by lisavanmansom** [comment]
Mijn ontwerp:
https://github.com/lisavanmansom/tribeforlife-squadpage/issues/1
