### ISSUE TITLE
Screenreader / tab test

### ISSUE THREAD

**Issue by lisavanmansom** [zoepje/your-tribe-for-life-squad-page#23]

**Comment by zoepje** [comment]
**Tabtest**

https://github.com/user-attachments/assets/82c87827-d7f2-4dd0-9b2a-70af30e33d51

De darkmode button en de filters kun je niet gebruiken als je door de website tabt.
Dit komt door dit:
https://github.com/zoepje/your-tribe-for-life-squad-page/blob/8b5a410c312b8ced3d39e259040f9471fe988650/squadpage/src/routes/%2Bpage.svelte#L175-L177
https://github.com/zoepje/your-tribe-for-life-squad-page/blob/8b5a410c312b8ced3d39e259040f9471fe988650/squadpage/src/routes/%2Bpage.svelte#L248-L250

Dit kan gefixt worden door de inputs buiten beeld te zetten ipv `visibility: hidden;`/`display: none;`

**Comment by zoepje** [comment]
**Screenreader:**
Wat moet gefixt worden:
1. Darkmode button wordt benoemd als checkbox en heeft geen beschrijvende naam van wat het doet.
1. Daarna zegt hij "no visible title to interect" en loopt hij vast. Als je met tab naar scroll gaat dan doet hij het pas weer.
2. Als je op de link scroll klikt dan krijg je dat je op een pagina bent zonder titel, omdat je eigenlijk niet naar een nieuwe pagina gaat.
1. Na scroll kom je op de lijst met namen en niet op het filter. Als je op het filter wilt komen moet je vanuit de lijst weer terug gaan.

Hoe kun je dit oplossen:
1. Je kunt een aria-label toevoegen aan de input om de gebruiker te laten weten waarvoor de checkbox is.
3. Ik denk dat de heading te ver genest is.
4. Ik weet niet hoe je dit kunt oplossen.
5. Ik heb geen idee hoe je dit zou kunnen oplossen. In de code staat het namelijk wel eerst filter dan pas lijst.
